"""empty message

Revision ID: 899e773b3d13
Revises: 
Create Date: 2024-06-06 20:35:56.925664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '899e773b3d13'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('capital_cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country', 'city', name='uq_capital_cities_country_city')
    )
    op.create_geospatial_index('idx_capital_cities_geom', 'capital_cities', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_capital_cities_city'), 'capital_cities', ['city'], unique=False)
    op.create_index(op.f('ix_capital_cities_country'), 'capital_cities', ['country'], unique=False)
    op.create_index(op.f('ix_capital_cities_id'), 'capital_cities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_capital_cities_id'), table_name='capital_cities')
    op.drop_index(op.f('ix_capital_cities_country'), table_name='capital_cities')
    op.drop_index(op.f('ix_capital_cities_city'), table_name='capital_cities')
    op.drop_geospatial_index('idx_capital_cities_geom', table_name='capital_cities', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('capital_cities')
    # ### end Alembic commands ###
